---
- name: Get temporary token for the sandbox (Assume Role)
  environment:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
  sts_assume_role:
    profile: "{{ aws_master_profile }}"
    role_arn: "arn:aws:iam::{{ account_id }}:role/OrganizationAccountAccessRole"
    role_session_name: "AssumeSandbox"
    region: aws-global
  register: assumed_role
  retries: 5
  delay: 15
  until: assumed_role is succeeded
