---
- when: rootid is not defined
  block:
    - name: Get the Root OU id
      command: >-
        {{ aws_cli }} --profile {{ aws_master_profile }}
        organizations list-roots
        --query 'Roots[0].[Id]'
        --output text
      register: _getrootid
      changed_when: false

    - set_fact:
        rootid: "{{ _getrootid.stdout }}"


- name: Get Destination OU id
  command: >-
    {{ aws_cli }} --profile {{ aws_master_profile }}
    organizations list-organizational-units-for-parent
    --parent-id {{ rootid }}
    --query 'OrganizationalUnits[?Name==`'{{ account_destination_ou }}'`].[Id]'
    --output text
  register: _getdestouid
  changed_when: false

- set_fact:
    destouid: "{{ _getdestouid.stdout }}"


- when: accounts_in_ou is not defined
  block:
    - name: Get the OU of the account
      command: >-
         {{ aws_cli }} --profile {{ aws_master_profile }}
         organizations list-parents --child-id {{ account_id }}
      register: r_ou
      changed_when: false

- when: >-
    destouid not in
    ( r_ou.stdout
    | from_json
    | json_query('Parents[].Id')
    | default([], true)
    )
  name: Move account to destination OU
  command: >-
    {{ aws_cli }} --profile {{ aws_master_profile }}
    organizations move-account
    --account-id {{ account_id }}
    --source-parent-id {{ rootid }}
    --destination-parent-id {{ destouid }}
  retries: 10
  delay: 120
