---
- environment:
    AWS_PROFILE: "{{ account_name }}"
  block:
    - name: Fetch all AWS regions
      command: >-
        {{ aws_cli }} ec2 describe-regions
        --query "Regions[].RegionName"
        --output json --region us-east-1
        --filter Name=opt-in-status,Values=opted-in,opt-in-not-required
      register: _regions
      changed_when: false
      retries: 5
      delay: 15
      until: _regions is succeeded

    - set_fact:
        all_regions: "{{ _regions.stdout | from_json | list }}"
