---
- environment:
    AWS_PROFILE: "{{ account_profile }}"
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
  block:
    - name: Create the public zone
      route53_zone:
        zone: "{{ account_name }}{{subdomain_base}}."
      register: _route53zone
      retries: 10
      delay: 10
      until: _route53zone is succeeded

    - set_fact:
        account_hosted_zone_id: "{{ _route53zone.zone_id }}"

    - name: Grab facts about the zone
      route53_info:
        query: hosted_zone
        hosted_zone_method: details
        hosted_zone_id: "{{ _route53zone.zone_id }}"
      register: _route53facts
      retries: 5
      delay: 30
      until: _route53facts is succeeded

    - name: Save NS records
      set_fact:
        ns_records: >-
          {{ _route53facts.DelegationSet.NameServers
          | map('regex_replace', '$', '.') }}

    - name: Set the NS records using the Delegation Set
      route53:
        state: present
        zone: "{{ account_name }}{{subdomain_base}}."
        record: "{{ account_name }}{{subdomain_base}}."
        type: NS
        value: "{{ ns_records }}"
        overwrite: true
      register: _route53zoneNS
      retries: 5
      delay: 30
      until: _route53zoneNS is succeeded

    - name: Add HostedZoneId to the report
      lineinfile:
        path: "{{ output_dir }}/{{ account_name }}_report.txt"
        line: "HostedZoneId: {{ _route53zone.zone_id }}"
        regexp: '^HostedZoneId: '

    - name: Add Zone name to the report
      lineinfile:
        path: "{{ output_dir }}/{{ account_name }}_report.txt"
        line: "subdomain_base_suffix: .{{ account_name }}{{subdomain_base}}"
        regexp: '^subdomain_base_suffix: '
