pipeline {
    agent any

    // disable concurrent builds
    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('Test') {
            steps {
                // Load the private repo git@github.com:rhpds/ocp-shared-clusters-configs.git

                dir('ocp-shared-clusters-configs') {
                    git branch: 'main',
                        credentialsId: 'ssh-key-ocp-shared-clusters-config',
                        url: 'git@github.com:rhpds/ocp-shared-clusters-configs.git'
                }

                
                // Use  credential sandbox-functional-tests-dev-creds as a file to load the credentials
                withCredentials([
                    file(credentialsId: 'sandbox-functional-tests-dev-creds', variable: 'CREDENTIALS_FILE'),
                    string(credentialsId: 'bw-ocp-shared-clusters-config-token', variable: 'BWS_ACCESS_TOKEN'),
                    string(credentialsId: 'bw-ocp-shared-clusters-config-project-id', variable: 'BWS_PROJECT_ID'),
                ]) {
                    sh 'tests/jenkins-run.sh'
                }
            }
        }
    }

    post {
        always {
            // This block will run regardless of success, failure, or abort
            archiveArtifacts artifacts: 'api.log'
            script {
                def artifactUrl = "${env.BUILD_URL}artifact/api.log"

                echo "API logs: ${artifactUrl}"
            }
        }
    }
}
