package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	pgx "github.com/jackc/pgx/v4"
	"github.com/rhpds/sandbox/cmd/sandbox-api/graph/model"
	"github.com/rhpds/sandbox/internal/models"
)

// Resources is the resolver for the resources field.
// Loads resources on demand from AWS, OCP, DNS, and IBM providers.
// Note: LoadResources updates the placement status in the database as a side effect.
func (r *placementResolver) Resources(ctx context.Context, obj *model.Placement) ([]any, error) {
	// Get the full placement from database to load resources
	placement, err := models.GetPlacementByServiceUuid(r.DbPool, obj.ServiceUUID)
	if err != nil {
		return nil, err
	}

	// Load resources from all providers (also updates placement status in DB)
	if err := placement.LoadResources(r.AwsProvider, r.OcpProvider, r.DnsProvider, r.IbmProvider); err != nil {
		return nil, err
	}

	// Update obj to reflect the latest status (for consistency in this response)
	obj.Status = placement.Status

	return placement.Resources, nil
}

// Placements is the resolver for the placements field.
func (r *queryResolver) Placements(ctx context.Context, status *string, serviceUUID *string, toCleanup *bool, annotations map[string]any, limit *int, offset *int) ([]*model.Placement, error) {
	filter := models.PlacementFilter{
		Status:      status,
		ServiceUuid: serviceUUID,
		ToCleanup:   toCleanup,
		Annotations: annotations,
		Limit:       limit,
		Offset:      offset,
	}

	placements, err := models.GetPlacementsFiltered(r.DbPool, filter)
	if err != nil {
		return nil, err
	}

	// Convert to GraphQL model
	result := make([]*model.Placement, len(placements))
	for i, p := range placements {
		result[i] = toGraphQLPlacement(&p)
	}

	return result, nil
}

// Placement is the resolver for the placement field.
func (r *queryResolver) Placement(ctx context.Context, id int) (*model.Placement, error) {
	p, err := models.GetPlacement(r.DbPool, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return toGraphQLPlacement(p), nil
}

// PlacementByServiceUUID is the resolver for the placementByServiceUuid field.
func (r *queryResolver) PlacementByServiceUUID(ctx context.Context, serviceUUID string) (*model.Placement, error) {
	p, err := models.GetPlacementByServiceUuid(r.DbPool, serviceUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return toGraphQLPlacement(p), nil
}

// Placement returns PlacementResolver implementation.
func (r *Resolver) Placement() PlacementResolver { return &placementResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type placementResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
