// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Placement struct {
	ID          int            `json:"id"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	ServiceUUID string         `json:"serviceUuid"`
	Status      string         `json:"status"`
	ToCleanup   bool           `json:"toCleanup"`
	Annotations map[string]any `json:"annotations,omitempty"`
	Request     any            `json:"request,omitempty"`
	// Resources associated with this placement (AWS, OCP, DNS, IBM sandboxes).
	// Loaded on demand from providers.
	Resources []any `json:"resources,omitempty"`
}

type Query struct {
}
