---
# INPUT
account_name: sandbox1
account_email: sandbox1@opentlc.com
account_user: student
#account_destination_ou
#account_id

operation: CREATE

# Listing all accounts in the organization is a costly operation
# it takes currently 47s to execute.
# Check the account only in certain scenario, like for a retry
check_account_list: false

available_after_reset: true
available_after_create: false
alias_suffix: '-gpte'
aws_master_profile: gpe-gucore
aws_region: us-east-1

account_profile: "{{ account_name }}"
aws_role_name: OrganizationAccountAccessRole

vault_file: ~/secrets/infra-sandbox-vault

subdomain_base: .opentlc.com
output_dir: '/tmp/output_dir'

ddns_key_name: mydynamickey
ddns_key_algorithm: hmac-sha512
ddns_port: 53
ddns_domain: opentlc.com
ddns_server: ipaserver

# yamllint disable-line rule:line-length
opentlc_admin_backdoor: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvZvn+GL0wTOsAdh1ikIQoqj2Fw/RA6F14O347rgKdpkgOQpGQk1k2gM8wcla2Y1o0bPIzwlNy1oh5o9uNjZDMeDcEXWuXbu0cRBy4pVRhh8a8zAZfssnqoXHHLyPyHWpdTmgIhr0UIGYrzHrnySAnUcDp3gJuE46UEBtrlyv94cVvZf+EZUTaZ+2KjTRLoNryCn7vKoGHQBooYg1DeHLcLSRWEADUo+bP0y64+X/XTMZOAXbf8kTXocqAgfl/usbYdfLOgwU6zWuj8vxzAKuMEXS1AJSp5aeqRKlbbw40IkTmLoQIgJdb2Zt98BH/xHDe9xxhscUCfWeS37XLp75J

# yamllint disable-line rule:line-length
ocpkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8c3m39CoyA3bbgQUui3MGlJOryfg98NwIj8UUOv+PCuTRiyNanZeirRnPzWBtPzrVXeqtfenJo1ehDt0SRoqlUvpE7IUgnJsM7XJaUmKiVJMI4WslgMQMsZQGol7n2h0jwvtXIQp44jTtX61G7HMIUoFjJNXCO5GCrj3w2SVAKMYcznKUXpVmrkjdiHTZHmDxArHKZ7Kew2jCNUMgEq+mcaINPovUybjD17rCiKJDV4JQvLFQH89BFTVkVBsc0+QAe9LoW6l0rMDSemTvFeHy7tD0qGxYehvnHreOH6Nn9j9iOlG0f4R9+M+8KaI3uqibjOhn/kOQLK/1mphg2NnJ

####################################
# variable for RESET operation
####################################
nuke_sandbox: true

aws_nuke_binary_path: aws-nuke
aws_nuke_legacy_binary_path: aws-nuke-legacy

aws_nuke_account_blacklist:
  - 017310218799 # Master account
  - 627202319003 # OPENTLC Events
  - 962799139175 # OPENTLC
  - 719622469867 # GPE (RHPDS prod)
  - 550201621713 # openshift BU
  - 124572886817 # AWS dev/test
  - 809721187735 # GPTE infrastructure
  - 384299329206 # GPTE ILT

aws_nuke_retries: 0

aws_nuke_filters: {}

# Resources to keep. This will be combined with aws_nuke_filters
aws_nuke_filters_default:
  IAMUser:
    - student

  Route53HostedZone:
    - "{{ account_name }}{{ subdomain_base }}."

  IAMRole:
    - config-rule-role
    - OrganizationAccountAccessRole
    - AWSServiceRoleForCloudTrail
    - AWSServiceRoleForElasticLoadBalancing
    - AWSServiceRoleForOrganizations
    - AWSServiceRoleForSupport
    - AWSServiceRoleForTrustedAdvisor
    - CloudabilityRole_OU
    - redhat-HCC-role

  IAMRolePolicy:
    - "OrganizationAccountAccessRole -> AdministratorAccess"
    - config-rule-role -> config-rule-policy
    - redhat-HCC-role -> redhat-HCC-policy
    - CloudabilityRole_OU -> CloudabilityAutomationPolicy
    - CloudabilityRole_OU -> CloudabilityMonitorResourcesPolicy
    - CloudabilityRole_OU -> CloudabilityVerificationPolicy

  IAMRolePolicyAttachment:
    - property: RoleName
      value: OrganizationAccountAccessRole

    - AWSServiceRoleForCloudTrail -> CloudTrailServiceRolePolicy
    - AWSServiceRoleForElasticLoadBalancing -> AWSElasticLoadBalancingServiceRolePolicy
    - AWSServiceRoleForGlobalAccelerator -> AWSGlobalAcceleratorSLRPolicy
    - AWSServiceRoleForMarketplaceLicenseManagement -> AWSMarketplaceLicenseManagementServiceRolePolicy
    - AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy
    - AWSServiceRoleForSSO -> AWSSSOServiceRolePolicy
    - AWSServiceRoleForServiceQuotas -> ServiceQuotasServiceRolePolicy
    - AWSServiceRoleForSupport -> AWSSupportServiceRolePolicy
    - AWSServiceRoleForTrustedAdvisor -> AWSTrustedAdvisorServiceRolePolicy
    - AWSServiceRoleForVPCTransitGateway -> AWSVPCTransitGatewayServiceRolePolicy

  IAMPolicy:
    - arn:aws:iam::{{ account_id }}:policy/config-rule-policy
    - arn:aws:iam::{{ account_id }}:policy/redhat-HCC-policy
    - redhat-HCC-policy

  EC2KeyPair:
    - opentlc_admin_backdoor
    - ocpkey

  CloudFormationStack:
    - roles

  CloudTrailTrail:
    - RHOrganization

  # The following resources cannot be delete, so skip them by default
  KMSAlias:
    - alias/aws/dynamodb
    - alias/aws/ebs
    - alias/aws/elasticfilesystem
    - alias/aws/es
    - alias/aws/glue
    - alias/aws/kinesisvideo
    - alias/aws/rds
    - alias/aws/redshift
    - alias/aws/s3
    - alias/aws/ssm
    - alias/aws/xray
    - type: glob
      value: alias/eks/*

  KMSKey:
    # AWS managed key
    - 019e63a9-089e-42d8-9125-9e8461923851
    - 73df181b-38b8-44b6-8488-f8226933e7bf
    - 6cadef27-c9cf-4024-82a3-1e0cdab6431f
    - af193208-b881-44d0-b420-aaa43bbce83c
    - f4b1b7ab-8d6f-464b-9ff3-c1a9e2520039
    - 5e386636-7213-40f4-a3eb-843a4072e755
    - 9c0396a9-72be-4d1e-8298-4615c07d03ab

  MediaConvertQueue:
    - Default

  # Default Plan and Vault cannot be deleted
  AWSBackupSelection:
    - property: Name
      value: aws/efs/automatic-backup-selection
  AWSBackupPlan:
    - property: Name
      value: aws/efs/automatic-backup-plan
  AWSBackupVault:
    - property: Name
      value: aws/efs/automatic-backup-vault
  AWSBackupVaultAccessPolicy:
    - aws/efs/automatic-backup-vault

  # Rejected VPC Endpoints cannot be deleted
  EC2VPCEndpointConnection:
    - property: State
      value: rejected

##############################
# POOL management
##############################

dynamodb_profile: "{{ aws_master_profile }}"
dynamodb_table: accounts
dynamodb_region: us-east-1

# local vars
account_altready_exists: false

force_create: false
update_stage: false

aws_cli: aws
